// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/6325588fa8044ae7b36a02c2
###
GET http://localhost:3000/contacts/6325590ea8044ae7b36a02c3
###
GET http://localhost:3000/contacts/63255957a8044ae7b36a02c4

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
